{
 "title": "Ingress Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "ingress",
    "label": "Ingress Name",
    "query": {
     "query": "label_values(kube_ingress_info{job=\"kubernetes-service-endpoints\"}, ingress)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ingress" },
  {
   "title": "Ingress Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Method and Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "  sum by (method, host, path)(\r\n    rate(\r\n      nginx_ingress_controller_request_duration_seconds_count{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Error Rate by Method and Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, host, path) (rate(nginx_ingress_controller_request_duration_seconds_count{\r\n  ingress =~ \"$ingress\",\r\n  status =~ \"[4-5].*\"\r\n}[5m])) / sum by (method, host, path) (rate(nginx_ingress_controller_request_duration_seconds_count{\r\n  ingress =~ \"$ingress\",\r\n}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n      nginx_ingress_controller_request_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n    nginx_ingress_controller_request_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le)(\r\n    rate(\r\n      nginx_ingress_controller_request_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Upstream Response Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le)(\r\n    rate(\r\n      nginx_ingress_controller_response_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n    nginx_ingress_controller_response_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n      nginx_ingress_controller_response_duration_seconds_bucket{\r\n        ingress =~ \"$ingress\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Upstream Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (\r\n  rate(\r\n      nginx_ingress_controller_ingress_upstream_latency_seconds_sum {\r\n        ingress =~ \"$ingress\",\r\n      }[5m]\r\n)) / sum (\r\n  rate(\r\n      nginx_ingress_controller_ingress_upstream_latency_seconds_count {\r\n        ingress =~ \"$ingress\",\r\n      }[5m]\r\n  )\r\n)",
     "legendFormat": ".5"
    }
   ]
  }
 ]
}