{
 "title": "Pod Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{namespace=~\"dev|qa\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Num of Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chart) (kube_pod_container_status_ready)"
    }
   ]
  },
  {
   "title": "Dev Namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chart) (kube_pod_container_status_ready{namespace=\"dev\"})"
    }
   ]
  },
  {
   "title": "QA Namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chart) (kube_pod_container_status_ready{namespace=\"qa\"})"
    }
   ]
  },
  {
   "title": "Other Namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chart) (kube_pod_container_status_ready{namespace!~\"dev|qa\"})"
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "deployment",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Num of Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (kube_replicaset_spec_replicas{namespace=\"$namespace\", replicaset=~\"$deployment.+\"})"
      }
     ]
    },
    {
     "title": "CPU Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (resource) (kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.+\"})"
      }
     ]
    },
    {
     "title": "CPU Limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (resource) (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.+\"})"
      }
     ]
    },
    {
     "title": "CPU Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (resource) (kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.+\"})"
      }
     ]
    },
    {
     "title": "CPU Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (resource) (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.+\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", image!=\"\", pod=~\"$deployment.+\"}[5m]) / on (container, pod) kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.+\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * max(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\", image!=\"\", pod=~\"$deployment.+\"} / on (container, pod) kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.+\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}